name: Copy Branch

on:
  push:
    branches:
      - collab  # Define the branch you want to trigger this action on

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create new dev branch
        run: |
          git checkout -b dev_new
          git push origin dev_new

      - name: Merge old dev to new
        run: |
          git checkout dev_new
          git merge origin/dev
          git push origin dev_new


      - name: Switch to new dev
        run: |
          git checkout dev
          # Check if dev_old branch exists before renaming
          if git show-ref --quiet refs/heads/dev_old; then
            git branch -m dev_old
            git push origin dev_old --delete
          fi
          git checkout dev_new
          git branch -m dev
          git push origin dev

      - name: Delete old dev branch
        run: |
          # Check if dev_old branch exists before deleting
          if git show-ref --quiet refs/heads/dev_old; then
            git push origin dev_old --delete
          fi
