name: Copy Branch

on:
  push:
    branches:
      - collab  # Define the branch you want to trigger this action on

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "ranjanpatra336@gmail.com"
          git config --global user.name "GitHub Actions"
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch branches from origin
        run: git fetch origin

      - name: Create new dev branch
        run: |
          git checkout -b dev_new
          git push origin dev_new
      - name: Set up GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.AZURETOKEN }}  # Using the default repository dispatch token
        run: |
          gh auth login --with-token <<<"${GH_TOKEN}"

      - name: Switch to new dev and clean up
        run: |
          gh pr create --base dev_new --head dev --title "Merge dev into dev_new"
          git checkout dev_new

